version: "3.6"
services:
  server1:
    build:
      context: ./socket-server
      dockerfile: Dockerfile
    # command: sh -c "python run.py"  # wait for db, then run
    container_name: server1
    ports:
      - 5200:5200
    # volumes:
    #  - ./app:/src/app

  client1:
    build:
      context: ./socket-client
      dockerfile: Dockerfile
    container_name: client1
    ports:
      - 1000:1000